/* eslint-disable @next/next/no-html-link-for-pages */
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        style={{
          fontFamily: "system-ui, sans-serif",
          maxWidth: 880,
          margin: "2rem auto",
        }}
      >
        <h1>Next.js Rendering Demo (CSR / SSR / SSG)</h1>
        <nav style={{ display: "flex", gap: 12, marginBottom: 24 }}>
          <a href="/">Home (SSG/ISR)</a>
          <a href="/ssr">SSR</a>
          <a href="/csr">CSR</a>
          <a href="/blog/hello-next">Blog: hello-next (SSG)</a>
          <a href="/blog/edge-cases">Blog: edge-cases (SSG)</a>
        </nav>
        {children}
      </body>
    </html>
  );
}
